//! Tauri command exposing the bundled BC MSP ICD-9 code set to the
//! frontend for post-generation validation of SOAP-note codes.

use std::collections::HashMap;

use medical_core::error::AppResult;

/// Returns all 7,122 BC MSP ICD-9 diagnostic codes as a sorted vector.
///
/// The frontend caches this once and checks emitted SOAP codes against
/// it, flagging any code not on the list. Memoized on the Rust side via
/// [`medical_core::icd9`]'s `LazyLock`, so repeated invocations are cheap.
#[tauri::command]
pub async fn get_icd9_code_set() -> AppResult<Vec<String>> {
    Ok(medical_core::icd9::code_set().iter().cloned().collect())
}

/// Returns the BC MSP code → official description map (7,122 entries).
///
/// The frontend's billing-code list shows an explaining title next to
/// each code. Notes generated by the SOAP prompt already carry a
/// model-written description ("ICD-9 Code: <code> — <description>"); this
/// map is the fallback for codes whose note text has none (hand-edited or
/// imported notes). Memoized via the same `LazyLock` indexes, so repeated
/// invocations are cheap.
#[tauri::command]
pub async fn get_icd9_descriptions() -> AppResult<HashMap<String, String>> {
    Ok(medical_core::icd9::code_index()
        .iter()
        .map(|(code, entry)| ((*code).clone(), entry.description.clone()))
        .collect())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn descriptions_cover_every_code_with_official_text() {
        let map = get_icd9_descriptions().await.expect("command must succeed");
        assert_eq!(map.len(), medical_core::icd9::code_set().len());
        // Raw MSP fragment — the frontend softens the ALL-CAPS styling for
        // display, but the wire value is verbatim (see icd9.rs `ENTRIES`).
        assert_eq!(map.get("847.2").map(String::as_str), Some("LUMBAR"));
        assert!(map.get("V70.0").is_some_and(|d| !d.is_empty()));
    }
}
