// Spellchecker wrapper. Loads the en-US Hunspell dictionary once via Vite
// asset imports (bundled at build time — no runtime network requests, no PHI
// leakage, complies with the local-only constraint), and combines its
// suggestions with a per-user wordlist persisted in SQLite + an in-memory
// session ignore set + a bundled medical-terms wordlist.
import nspell from 'nspell';
// Vite resolves these at build time and inlines them as URLs.
// dictionary-en ships the Hunspell .aff/.dic files via its package exports.
import affUrl from 'dictionary-en/index.aff?url';
import dicUrl from 'dictionary-en/index.dic?url';
// Bundled medical wordlist. Generated by scripts/build_medical_wordlist.mjs
// from CodeSante/medical-wordlist (WTFPL, derived from Wikidata CC0 data).
import medicalUrl from './medical_terms.txt?url';
import { listUserDict, addUserDict, removeUserDict } from '../../../api/userDictionary';

export interface Spellchecker {
  /** Returns true once the dictionary has loaded. */
  readonly ready: boolean;
  /** Number of bundled medical terms loaded (0 until load() completes). */
  readonly medicalTermCount: number;
  /** Load the dictionary (idempotent; safe to call multiple times). */
  load(): Promise<void>;
  /** Returns true when the word is in the dictionary OR user wordlist
   *  OR session ignore list OR (when enabled) the bundled medical wordlist. */
  check(word: string): boolean;
  /** Up to N suggestions for a misspelled word (empty if no suggestions). */
  suggest(word: string, max?: number): string[];
  /** Add to user dictionary (persisted). Returns true if newly added. */
  addToUserDict(word: string): Promise<boolean>;
  /** Remove from user dictionary (persisted). Returns true if a row was deleted. */
  removeFromUserDict(word: string): Promise<boolean>;
  /** Add to session ignore (not persisted). */
  ignoreInSession(word: string): void;
  /** Enable/disable the bundled medical wordlist in check() lookups. */
  setMedicalEnabled(enabled: boolean): void;
  /** Reload the user wordlist from the backend (used after a remote sync
   *  pushes new words to this machine). Safe to call before load() completes
   *  (it will await the load first). */
  reloadUserWords(): Promise<void>;
}

class SpellcheckerImpl implements Spellchecker {
  private nspell: ReturnType<typeof nspell> | null = null;
  private userWords = new Set<string>(); // lowercased
  private sessionIgnored = new Set<string>(); // lowercased
  private medicalWords = new Set<string>(); // lowercased
  private medicalEnabled = true;
  private loadingPromise: Promise<void> | null = null;

  /** Common medical abbreviations that Hunspell doesn't know but should
   *  never be flagged. Checked case-insensitively. */
  private static MEDICAL_ABBREVIATIONS = new Set([
    'bid', 'tid', 'qid', 'prn', 'po', 'iv', 'im', 'sc', 'sq', 'sl',
    'ac', 'pc', 'hs', 'qd', 'qod', 'qhs', 'qam', 'qpm',
    'mg', 'ml', 'cc', 'mcl', 'meq', 'mmol', 'iu', 'mcg', 'ng',
    'nacl', 'kcl', 'hctz', 'bpm', 'mmhg', 'wbc', 'rbc', 'hgb',
    'pt', 'inr', 'bmp', 'cmp', 'cbc', 'ua', 'cxr', 'ekg', 'ecg',
    'ct', 'mri', 'us', 'bid', 'npo', 'od', 'os', 'ou', 'au', 'ad', 'as',
    'apap', 'ns', 'lr', 'd5w', 'd5ns', 'd51⁄2ns',
    's/p', 'c/w', 'r/o', 'd/c', 'f/u', 'sxs', 'tx', 'dx', 'hx', 'px',
    'sob', 'cp', 'loc', 'doe', 'pnd', 'orthopnea',
    'copd', 'chf', 'cad', 'pad', 'uti', 'gerd', 'pud', 'ibd', 'ibs',
    'bph', 'dvt', 'pe', 'tia', 'cva', 'saH', 'sak',
    'tsh', 't3', 't4', 'hba1c', 'esr', 'crp', 'alt', 'ast', 'alp',
    'bun', 'cr', 'egfr', 'gba',
    'ssri', 'snri', 'ace', 'arb', 'ppi', 'nsaid', 'dmard',
  ]);

  get ready(): boolean {
    return this.nspell !== null;
  }

  get medicalTermCount(): number {
    return this.medicalWords.size;
  }

  async load(): Promise<void> {
    if (this.loadingPromise) return this.loadingPromise;
    this.loadingPromise = (async () => {
      const [affRes, dicRes, medicalRaw, userListRaw] = await Promise.all([
        fetch(affUrl).then((r) => r.text()),
        fetch(dicUrl).then((r) => r.text()),
        fetch(medicalUrl).then((r) => r.text()).catch(() => ''),
        listUserDict().catch(() => [] as string[]),
      ]);
      this.nspell = nspell(affRes, dicRes);
      this.applyUserWords(userListRaw);
      for (const line of medicalRaw.split('\n')) {
        const w = line.trim();
        if (w) this.medicalWords.add(w);
      }
    })();
    return this.loadingPromise;
  }

  /** Replace the in-memory user wordlist with a fresh set from the backend. */
  private applyUserWords(words: string[]): void {
    this.userWords = new Set(words.map((w) => w.toLowerCase()));
  }

  /** Reload the user wordlist from the backend (used after a remote sync
   *  pushes new words to this machine). Awaits the initial dictionary load
   *  first so we don't race with it. */
  async reloadUserWords(): Promise<void> {
    await this.load();
    try {
      const words = await listUserDict();
      this.applyUserWords(words);
    } catch (e) {
      console.error('Failed to reload user dictionary:', e);
    }
  }

  check(word: string): boolean {
    if (!this.nspell) return true; // pre-load: don't flag anything
    const lower = word.toLowerCase();
    if (this.userWords.has(lower)) return true;
    if (this.sessionIgnored.has(lower)) return true;
    if (this.medicalEnabled && this.medicalWords.has(lower)) return true;

    // Handle camelCase: split on case boundaries and check each part.
    // e.g., "patientName" → ["patient", "Name"], each checked individually.
    if (/[a-z][A-Z]/.test(word)) {
      const parts = word.split(/(?=[A-Z])/).filter((p) => p.length > 0);
      if (parts.length > 1) {
        return parts.every((part) => this.checkInternal(part));
      }
    }

    return this.checkInternal(word);
  }

  /** Core word check without camelCase splitting (used recursively). */
  private checkInternal(word: string): boolean {
    const lower = word.toLowerCase();
    if (this.userWords.has(lower)) return true;
    if (this.sessionIgnored.has(lower)) return true;
    if (this.medicalEnabled && this.medicalWords.has(lower)) return true;
    if (SpellcheckerImpl.MEDICAL_ABBREVIATIONS.has(lower)) return true;
    return this.nspell!.correct(word);
  }

  suggest(word: string, max = 5): string[] {
    if (!this.nspell) return [];
    return this.nspell.suggest(word).slice(0, max);
  }

  async addToUserDict(word: string): Promise<boolean> {
    const newlyAdded = await addUserDict(word);
    this.userWords.add(word.toLowerCase());
    return newlyAdded;
  }

  async removeFromUserDict(word: string): Promise<boolean> {
    const removed = await removeUserDict(word);
    this.userWords.delete(word.toLowerCase());
    return removed;
  }

  ignoreInSession(word: string): void {
    this.sessionIgnored.add(word.toLowerCase());
  }

  setMedicalEnabled(enabled: boolean): void {
    this.medicalEnabled = enabled;
  }
}

let singleton: SpellcheckerImpl | null = null;

/**
 * Get the lazily-initialized singleton spellchecker. The first call starts
 * the async dictionary load; subsequent calls return the same instance.
 * Use `.ready` to gate UI that depends on the dictionary being loaded.
 */
export function getSpellchecker(): Spellchecker {
  if (!singleton) singleton = new SpellcheckerImpl();
  return singleton;
}
