//! Generates the README.md that accompanies a training-corpus export.
//!
//! Documents the JSONL format, redaction caveats, and points the
//! clinician at typical fine-tuning recipes.

pub fn render_readme(
    pair_count: u32,
    base_models: &[String],
    ferri_scribe_version: &str,
) -> String {
    let models = if base_models.is_empty() {
        "(unspecified)".to_string()
    } else {
        base_models.join(", ")
    };
    format!(
        r#"# Training corpus export

Exported from FerriScribe v{ferri_scribe_version}.

## Contents

- `train.jsonl` — {pair_count} training pairs in OpenAI chat-completion format.
- `manifest.json` — corpus statistics, base-model filter, redaction settings.
- `README.md` — this file.

## Format

Each line of `train.jsonl` is a JSON object with this shape:

```json
{{"messages": [
  {{"role": "system", "content": "<prompt template identifier>"}},
  {{"role": "user", "content": "<redacted transcript + context>"}},
  {{"role": "assistant", "content": "<redacted final SOAP note>"}}
]}}
```

## Base model

Drafts in this corpus were generated by: **{models}**.

Fine-tune a compatible base model for best results. Mixing drafts from
different base models into a single fine-tune typically produces a
confused model — the export already filters to your chosen base.

## Redaction caveats

Redaction is rule-based, not ML-based. Known limitations:

- Patient names not stored in the recording's `patient_name` column
  are NOT redacted (e.g., second/third parties mentioned in the note).
- Provider names are only partially covered (depends on the
  `saved_recipients` list; aggressive mode covers more).
- Free-text re-identification through context (rare diagnosis + small
  town + age) is not addressed by this redaction.
- Review at least a random sample of the output before using it for
  training, especially before sharing the corpus with anyone else.

## Suggested fine-tuning recipes

This is a small personal corpus. **LoRA / QLoRA** is the right approach,
not full fine-tuning.

Typical hyperparameters for a personal-style fine-tune:

- LoRA rank: 16
- LoRA alpha: 32
- Learning rate: 2e-4
- Epochs: 2–3
- Batch size: 1–4 (depending on context length)

Common toolchains that accept this format directly:

- [unsloth](https://github.com/unslothai/unsloth) — fastest on a single GPU
- [mlx-lm](https://github.com/ml-explore/mlx-examples/tree/main/llms) — Apple Silicon native
- [torchtune](https://github.com/pytorch/torchtune) — official PyTorch
- [axolotl](https://github.com/OpenAccess-AI-Collective/axolotl) — config-driven

## After training

Pull the resulting model into Ollama:

```
ollama create soap-personal-v1 -f ./Modelfile
```

It will then appear in FerriScribe's Ollama provider list.

## Privacy reminder

This corpus may contain residual identifiers despite redaction. Keep
it on the same device as the source data, or transfer only over
encrypted channels to a trusted training environment.
"#,
        pair_count = pair_count,
        models = models,
        ferri_scribe_version = ferri_scribe_version,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn readme_includes_pair_count_and_models() {
        let out = render_readme(123, &["llama3:70b".to_string()], "0.10.56");
        assert!(out.contains("123 training pairs"));
        assert!(out.contains("llama3:70b"));
        assert!(out.contains("0.10.56"));
    }

    #[test]
    fn readme_handles_empty_model_list() {
        let out = render_readme(5, &[], "0.10.56");
        assert!(out.contains("(unspecified)"));
    }
}
