// Generated by Rust: format_transcript_with_speakers (writer/reader
// symmetry fixture — see TranscriptView.formatter-roundtrip.test.ts).
// DO NOT EDIT BY HAND — regenerate with:
//   cargo test -p rust-medical-assistant regenerate_formatter_fixture -- --ignored
// Pinned byte-exact on the Rust side by checked_in_fixture_equals_formatter_output.
export { default as default } from './formatter-speaker-unassigned.txt?raw';
