[package]
name = "medical-sharing"
version.workspace = true
edition.workspace = true

[dependencies]
medical-core = { path = "../core" }
medical-security = { path = "../security" }
axum = { version = "0.7", features = ["macros"] }
tokio = { workspace = true }
tokio-util = { workspace = true }
reqwest = { workspace = true }
hyper = "1"
hyper-util = { version = "0.1", features = ["client", "client-legacy", "tokio"] }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
rand = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
base64 = { workspace = true }
urlencoding = { workspace = true }
mdns-sd = "0.13"
rusqlite = { version = "0.32", features = ["bundled-sqlcipher-vendored-openssl"] }
keyring = { version = "3", features = ["apple-native", "windows-native", "sync-secret-service"] }
dirs = { workspace = true }
hostname = "0.4"
zip = "2"
flate2 = "1"
tar = "0.4"
futures-util = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true }
